;;;(foreign-funcall "MessageBoxW" :pointer (null-pointer) (:string :encoding :utf-16le) "Пока нету!" (:string :encoding :utf-16le) "Сообщение" :int #x40 :boolean)
(defpackage :aiku (:use :common-lisp :cffi))
(in-package :aiku)
(load "~/project/geo/error-message-cffi.lisp")
(mapcar #'load-foreign-library '("user32.dll" "kernel32.dll" "gdi32.dll"))
(defcallback (dialogproc :convention :stdcall) :int32 ((hwnd :int32) (umsg :int32) (wparam :int32) (lparam :int32)) #x0)
(defcstruct point (x :short) (y :short))
(defcstruct message (hwnd :uint32) (msg :uint) (wparam :int32) (lparam :int32) (time :int32) (pt :pointer))
(let* ((hinstance (foreign-funcall "GetModuleHandleA" :int32 #x0 :int32))
       (hdlg (foreign-funcall ("CreateWindowExA" :convention :stdcall)
			      :int32 #x0 :string "static" :string "name" :int32 #x04cf0044 :int32 #x100 :int32 #x100 :int32 #x100 :int32 #x100 :int32 #x0 :int32 #x0 :int32 hinstance :int32 #x0 :int32)))
    (if (zerop hdlg) (error-message))
    (with-foreign-object (dlgproc 'dialogproc )
	(if (zerop (foreign-funcall ("SetWindowLongPtr" :convention :stdcall) :int32 hdlg :int32 #x4 :pointer (get-callback dlgproc) :int32))
	    (when (error-message))
	    (with-foreign-object (msg '(:struct message))
		(foreign-funcall ("ShowWindow" :convention :stdcall) :int32 hdlg :int32 #x3 :int32)
		(foreign-funcall ("UpdateWindow" :convention :stdcall) :int32 hdlg :int32)
		(loop while (not (foreign-funcall ("GetMessageA" :convention :stdcall) :pointer msg :int32 hdlg :uint #x0 :uint #x0 :int32))
		      do (unless (zerop (foreign-funcall ("IsDialogMessage" :convention :stdcall) :int32 hdlg :pointer msg :int32))
			     (foreign-funcall ("TranslateMessage" :convention :stdcall) :pointer msg :int32)
			     (foreign-funcall ("DispatchMessageA" :convention :stdcall) :pointer msg :int32))))))
    (foreign-funcall ("ExitProcess" :convention :stdcall) :int32 #x0 :int32))
